@extends('layouts.app')

@section('content')
@php($statusStyle=['menunggu'=>'bg-amber-100 text-amber-700','diproses'=>'bg-blue-100 text-blue-700','disetujui'=>'bg-emerald-100 text-emerald-700','ditolak'=>'bg-red-100 text-red-700'])
<div class="max-w-6xl mx-auto">
    <div class="mb-6"><h1 class="text-2xl font-extrabold text-slate-800">Pengajuan Sekolah</h1><p class="mt-1 text-sm text-slate-500">Pilih jenis pengajuan yang dibutuhkan, lalu lengkapi data dan lampirannya.</p></div>
    <section class="mb-8"><div class="mb-3 flex items-center justify-between"><h2 class="text-sm font-extrabold uppercase tracking-wider text-slate-600">Buat Pengajuan Baru</h2><a href="{{ route('operator.pengajuan.create') }}" class="text-xs font-bold text-blue-600 hover:underline">Form pengajuan umum →</a></div><div class="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">@forelse($jenisPengajuans as $jenis)<a href="{{ route('operator.pengajuan.create',['jenis'=>$jenis->id]) }}" class="group rounded-2xl border border-slate-200 bg-white p-5 shadow-sm transition hover:-translate-y-1 hover:border-blue-200 hover:shadow-lg"><div class="flex items-start justify-between gap-3"><div class="grid h-9 w-9 place-items-center rounded-xl bg-blue-50 text-sm font-extrabold text-blue-600">{{ $loop->iteration }}</div><span class="text-blue-500 transition group-hover:translate-x-1">→</span></div><h3 class="mt-4 text-sm font-extrabold leading-6 text-slate-800">{{ $jenis->nama }}</h3><p class="mt-2 text-xs leading-5 text-slate-500">{{ $jenis->deskripsi ?: 'Klik untuk mulai mengisi pengajuan.' }}</p></a>@empty<div class="col-span-full rounded-xl border border-dashed border-slate-300 bg-white p-6 text-sm text-slate-400">Belum ada jenis pengajuan yang tersedia. Hubungi admin.</div>@endforelse</div></section>
    <section><div class="mb-3 flex items-center justify-between"><h2 class="text-sm font-extrabold uppercase tracking-wider text-slate-600">Riwayat Pengajuan</h2></div><div class="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div class="overflow-x-auto"><table class="min-w-full text-sm"><thead class="bg-slate-50 text-left text-xs uppercase tracking-wider text-slate-500"><tr><th class="px-5 py-4">Pengajuan</th><th class="px-5 py-4">Tanggal</th><th class="px-5 py-4">Status</th><th class="px-5 py-4">Keterangan Admin</th><th class="px-5 py-4 text-right">Aksi</th></tr></thead><tbody class="divide-y divide-slate-100">@forelse($pengajuans as $item)<tr><td class="px-5 py-4"><p class="font-bold text-slate-800">{{ $item->judul }}</p><p class="mt-1 text-xs text-blue-600">{{ $item->jenisPengajuan?->nama ?? 'Jenis belum dipilih' }}</p>@if($item->lampiran)<a class="text-xs text-slate-500 hover:underline" target="_blank" href="{{ asset('storage/'.$item->lampiran) }}">Lihat lampiran</a>@endif</td><td class="px-5 py-4 text-slate-500">{{ $item->submitted_at?->translatedFormat('d M Y') }}</td><td class="px-5 py-4"><span class="rounded-full px-2.5 py-1 text-xs font-bold {{ $statusStyle[$item->status] }}">{{ ucfirst($item->status) }}</span></td><td class="max-w-xs px-5 py-4 text-xs text-slate-500">{{ $item->keterangan_admin ?: 'Belum ada keterangan.' }}</td><td class="px-5 py-4 text-right">@if(in_array($item->status,['menunggu','ditolak']))<a class="text-xs font-bold text-blue-600 hover:underline" href="{{ route('operator.pengajuan.edit',$item) }}">Edit</a><form class="inline" method="POST" action="{{ route('operator.pengajuan.destroy',$item) }}" onsubmit="return confirm('Hapus pengajuan ini?')">@csrf @method('DELETE')<button class="ml-3 text-xs font-bold text-red-600 hover:underline">Hapus</button></form>@endif</td></tr>@empty<tr><td colspan="5" class="px-5 py-14 text-center text-slate-400">Belum ada pengajuan.</td></tr>@endforelse</tbody></table></div></div><div class="mt-5">{{ $pengajuans->links() }}</div></section>
</div>
@endsection
