@extends('layouts.app')

@push('styles')
<link href="https://cdn.quilljs.com/1.3.7/quill.snow.css" rel="stylesheet">
<style>.ql-toolbar.ql-snow{border-color:#e2e8f0;border-radius:.5rem .5rem 0 0;background:#f8fafc}.ql-container.ql-snow{border-color:#e2e8f0;border-radius:0 0 .5rem .5rem;font:inherit}.ql-editor{min-height:240px;line-height:1.75}</style>
@endpush

@section('content')
<div class="max-w-3xl mx-auto"><a href="{{ route('pengumuman.index') }}" class="text-sm font-bold text-blue-600">← Pengumuman</a><h1 class="mt-3 text-2xl font-extrabold text-slate-800">{{ $pengumuman->exists ? 'Edit Pengumuman' : 'Buat Pengumuman' }}</h1><p class="mt-1 text-sm text-slate-500">Gunakan editor untuk menambahkan heading, daftar, tautan, dan format artikel.</p>
<form id="pengumuman-form" class="mt-6 space-y-5" method="POST" enctype="multipart/form-data" action="{{ $pengumuman->exists ? route('pengumuman.update',$pengumuman) : route('pengumuman.store') }}">@csrf @if($pengumuman->exists) @method('PUT') @endif
<section class="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><label class="block text-sm font-bold text-slate-700">Judul Pengumuman<input class="mt-2 w-full rounded-lg border border-slate-200 px-3 py-2.5 font-normal" name="judul" value="{{ old('judul',$pengumuman->judul) }}" required></label>@error('judul')<p class="mt-1 text-xs text-red-600">{{ $message }}</p>@enderror
<div class="mt-5"><label class="block text-sm font-bold text-slate-700">Isi Pengumuman</label><div id="quill-editor" class="mt-2"></div><textarea id="isi-input" name="isi" class="hidden">{{ old('isi',$pengumuman->isi) }}</textarea><p class="mt-2 text-xs text-slate-400">Gunakan heading, format teks, daftar, kutipan, dan tautan seperti pada Informasi.</p>@error('isi')<p class="mt-1 text-xs text-red-600">{{ $message }}</p>@enderror</div>
<div class="mt-5 grid gap-4 sm:grid-cols-2"><label class="text-sm font-bold text-slate-700">Gambar <span class="font-normal text-slate-400">(opsional)</span><input class="mt-2 block w-full rounded-lg border border-dashed border-slate-300 p-3 text-sm font-normal" type="file" name="gambar" accept="image/jpeg,image/png,image/webp"></label><label class="text-sm font-bold text-slate-700">Lampiran File <span class="font-normal text-slate-400">(opsional)</span><input class="mt-2 block w-full rounded-lg border border-dashed border-slate-300 p-3 text-sm font-normal" type="file" name="lampiran" accept=".pdf,.doc,.docx,.xls,.xlsx,.ppt,.pptx"></label></div><p class="mt-2 text-xs text-slate-400">Gambar maksimal 4 MB. Lampiran PDF, Word, Excel, atau PowerPoint maksimal 10 MB.</p>@if($pengumuman->gambar)<a class="mt-2 inline-block text-xs font-bold text-blue-600" target="_blank" href="{{ asset('storage/'.$pengumuman->gambar) }}">Lihat gambar saat ini</a>@endif @if($pengumuman->lampiran)<a class="ml-3 mt-2 inline-block text-xs font-bold text-blue-600" target="_blank" href="{{ asset('storage/'.$pengumuman->lampiran) }}">Lihat lampiran saat ini</a>@endif
<div class="mt-5 grid gap-4 sm:grid-cols-2"><label class="text-sm font-bold text-slate-700">Waktu Terbit<input class="mt-2 w-full rounded-lg border border-slate-200 px-3 py-2.5 font-normal" type="datetime-local" name="published_at" value="{{ old('published_at', optional($pengumuman->published_at)->format('Y-m-d\TH:i')) }}"></label><label class="text-sm font-bold text-slate-700">Status<select class="mt-2 w-full rounded-lg border border-slate-200 px-3 py-2.5 font-normal" name="is_active"><option value="1" @selected(old('is_active',$pengumuman->is_active ?? true)==1)>Aktif</option><option value="0" @selected(old('is_active',$pengumuman->is_active ?? true)==0)>Nonaktif</option></select></label></div></section><button class="rounded-lg bg-blue-600 px-5 py-3 text-sm font-bold text-white hover:bg-blue-700">Simpan Pengumuman</button></form></div>
@endsection

@push('scripts')
<script src="https://cdn.quilljs.com/1.3.7/quill.min.js"></script><script>const quill=new Quill('#quill-editor',{theme:'snow',modules:{toolbar:[[{header:[2,3,false]}],['bold','italic','underline'],[{list:'ordered'},{list:'bullet'}],['blockquote','link'],['clean']]}}),isiInput=document.getElementById('isi-input');if(isiInput.value)quill.root.innerHTML=isiInput.value;document.getElementById('pengumuman-form').addEventListener('submit',()=>isiInput.value=quill.root.innerHTML);</script>
@endpush
