@extends('layouts.app')

@section('content')
<div class="max-w-3xl mx-auto"><a class="text-sm font-bold text-blue-600" href="{{ route('panduan.index') }}">← Panduan Operator</a><h1 class="mt-3 text-2xl font-extrabold text-slate-800">{{ $panduan->exists ? 'Edit Panduan' : 'Tambah Panduan' }}</h1><form class="mt-6 space-y-5" method="POST" action="{{ $panduan->exists ? route('panduan.update', $panduan) : route('panduan.store') }}">@csrf @if($panduan->exists) @method('PUT') @endif<section class="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><label class="block text-sm font-bold text-slate-700">Judul Panduan<input class="mt-2 w-full rounded-lg border border-slate-200 px-3 py-2.5 font-normal" name="judul" value="{{ old('judul', $panduan->judul) }}" required></label>@error('judul')<p class="mt-1 text-xs text-red-600">{{ $message }}</p>@enderror<label class="mt-5 block text-sm font-bold text-slate-700">Jenis Panduan<select id="tipe-panduan" class="mt-2 w-full rounded-lg border border-slate-200 px-3 py-2.5 font-normal" name="tipe"><option value="artikel" @selected(old('tipe', $panduan->tipe) === 'artikel')>Artikel</option><option value="video" @selected(old('tipe', $panduan->tipe) === 'video')>Video</option></select></label><div id="artikel-fields" class="mt-5"><label class="block text-sm font-bold text-slate-700">Isi Artikel<textarea class="mt-2 min-h-56 w-full rounded-lg border border-slate-200 px-3 py-2.5 font-normal leading-7" name="konten">{{ old('konten', $panduan->konten) }}</textarea></label>@error('konten')<p class="mt-1 text-xs text-red-600">{{ $message }}</p>@enderror</div><div id="video-fields" class="mt-5"><label class="block text-sm font-bold text-slate-700">Link Video<input class="mt-2 w-full rounded-lg border border-slate-200 px-3 py-2.5 font-normal" name="video_url" value="{{ old('video_url', $panduan->video_url) }}" placeholder="https://www.youtube.com/watch?v=..."></label><p class="mt-1 text-xs text-slate-400">Gunakan link YouTube, Google Drive, atau video lain yang dapat dibuka operator.</p>@error('video_url')<p class="mt-1 text-xs text-red-600">{{ $message }}</p>@enderror</div><div class="mt-5 grid gap-4 sm:grid-cols-2"><label class="text-sm font-bold text-slate-700">Urutan<input class="mt-2 w-full rounded-lg border border-slate-200 px-3 py-2.5 font-normal" type="number" min="1" name="urutan" value="{{ old('urutan', $panduan->urutan ?? 1) }}" required></label><label class="text-sm font-bold text-slate-700">Status<select class="mt-2 w-full rounded-lg border border-slate-200 px-3 py-2.5 font-normal" name="is_active"><option value="1" @selected(old('is_active', $panduan->is_active ?? true) == 1)>Aktif</option><option value="0" @selected(old('is_active', $panduan->is_active ?? true) == 0)>Nonaktif</option></select></label></div></section><button class="rounded-lg bg-blue-600 px-5 py-3 text-sm font-bold text-white hover:bg-blue-700">Simpan Panduan</button></form></div>
@endsection

@push('scripts')
<script>const tipePanduan=document.getElementById('tipe-panduan'),artikelFields=document.getElementById('artikel-fields'),videoFields=document.getElementById('video-fields');function togglePanduanFields(){const artikel=tipePanduan.value==='artikel';artikelFields.classList.toggle('hidden',!artikel);videoFields.classList.toggle('hidden',artikel)}tipePanduan.addEventListener('change',togglePanduanFields);togglePanduanFields();</script>
@endpush
